### PR TITLE
fixes #36, switch to HTTP/1.0 and drop `Connection: keep-alive` from httpclient

### LINKED ISSUE #36: httpclient doesn't support chunked transfer encoding when receiving response
for example, parity ethereum client uses `Transfer-Encoding: chunked` and no `Content-Length` field.
this make httpclient unusable to perform rpc

### PR DESCRIPTION
**Pull request by jangko**

### CODE REVIEW

**Comment by coffeepots** [comment]
Also I'm wondering how easy it would be to add some simple tests for the chunking. @jangko would this be easy for you to set up?

**Comment by jangko** [comment]
> would this be easy for you to set up?

honestly, I have no idea where to start, that's why I left it blank.
Does it require me to modify the server too?
any clues perhaps?

**Comment by cheatfate** [comment]
@jangko chunked transfer encoding is not supported by `HTTP/1.0`, and because `geth` properly supports HTTP specification you can use `HTTP/1.0` requests and avoid `chunked` answers.

`nim-json-rpc` is also not the right place for `chunked` decoder.

**Comment by jangko** [comment]
luckily, parity also support `HTTP/1.0`.
does it mean we also drop `Connection: keep-alive` field too when connecting with HTTP/1.0?
is that acceptable?

**Comment by jangko** [comment]
switching to `HTTP/1.0` and removing `Connection: keep-alive` prove to be more problematic.
I think I will go through the hard way by putting it into httputils and implement chunked transfer decoding

**Comment by jangko** [comment]
I didn't say about speed, I've located the problem inside asyncdispatch2, perhaps we can pending that chunked transfer problem later and for now we can switch to HTTP/1.0 and drop keep-alive connection.

**Comment by coffeepots** [comment]
@jangko We've been discussing the chunking work and have come to the conclusion that we should stick with HTTP 1.0 for now (which you've already done here) and later have fully genericised chunking code further up in the tool chain.

With that in mind, can you remove the chunking code from this PR for now and will look at implementing it later.

**Comment by coffeepots** [comment]
@jangko We've been discussing the chunking work and have come to the conclusion that we should stick with HTTP 1.0 for now (which you've already done here) and later have fully genericised chunking code further up in the tool chain.

**Comment by jangko** [comment]
done

**Comment by jangko** [comment]
closed in favor of 6a0b0ff30d602e59056d1558662667ae5700d09c

**Pull request closed without merging**
